FROM node:16-alpine AS deps

ENV DISABLE_ESLINT_PLUGIN=true
ENV SKIP_PREFLIGHT_CHECK=true
ENV TSC_COMPILE_ON_ERROR=true

WORKDIR .

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY packages/client/package.json ./packages/client/package.json
COPY packages/client/yarn.lock ./packages/client/yarn.lock

RUN yarn --cwd ./packages/client install

COPY . .

RUN yarn --cwd ./packages/client build



FROM nginx:latest

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=deps ./packages/client/build /usr/share/nginx/html

EXPOSE 80
